Add support for post-scripts like postinstall, poststart, postbuild etc.
danielhuang/cotton pull request #92
Opened 2022-10-04 10:19 UTC by b4s36t4

#86

2022-10-06 18:02 UTC, b4s36t4 commented
@danielhuang can you review this if possible?

2022-10-06 18:21 UTC, danielhuang requested changes
This is a good start! However, it only supports the user-specified `postinstall` script in the project itself, not the necessary scripts used by some packages used as dependencies. 

The installation process currently works like this:
1. Make sure that the intended layout of `node_modules` is determined. If there are packages needed and the metadata is not yet known, fetch the metadata from the registry.
2. For each intended package, begin downloading the tarball that contains the files inside that package. The first 2 steps will happen concurrently, by starting the download process immediately after the metadata is known.
3. Once step 1 is complete, begin constructing `node_modules`. It would go through each package, wait for the download process (if needed), and hardlink the files to the target location.

In order to fully support `postinstall` scripts, certain dependencies needs to be completed before executing the intended scripts. For example, `electron` uses `pump` (a transitive dependency) as part of its `postinstall` in order to download a compiled artifact. That would need `electron`'s `postinstall` to wait on all of its dependencies.

2022-10-06 18:21 UTC, danielhuang commented on src/main.rs
> +    let script_key: &str = &("post".to_owned() + &name.to_owned());
This can be replaced with `format!`

2022-10-06 18:21 UTC, danielhuang commented on src/main.rs
> +    PROGRESS_BAR.suspend(|| println!("Running {}", script_key));
`PROGRESS_BAR` has a `println` method. `.suspend` is not needed here.

2022-10-06 18:21 UTC, danielhuang commented on src/main.rs
> +        exit(exit_code);
This will exit the entire process.

2023-03-04 22:07 UTC, danielhuang commented
Install scripts is now supported. See #86.

2023-03-04 22:07 UTC, closed without merging